import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { AuthSession } from '../../services/auth-session';
import { InboxItem, OperationsApi, ProfessionalAppointment } from '../../services/operations-api';
@Component({selector:'app-operations-panel',imports:[CommonModule,DatePipe],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<main class="min-h-screen bg-[#f8f9ff] p-5 sm:p-10"><section class="mx-auto max-w-4xl rounded-2xl bg-white p-6 shadow-sm"><div class="flex justify-between"><div><p class="text-xs font-bold uppercase tracking-widest text-[#006ef4]">Fase 6 · Operación</p><h1 class="mt-2 text-2xl font-extrabold text-[#002777]">{{session.role()==='doctor'?'Mi agenda profesional':'Bandeja administrativa'}}</h1></div><button (click)="load()" class="rounded-lg border px-3 py-2 text-sm font-bold text-[#002777]">Actualizar</button></div>@if(error()){<p class="mt-4 rounded bg-[#ffdad6] p-3 text-sm text-[#93000a]">{{error()}}</p>}@if(message()){<p class="mt-4 rounded bg-[#e5f5e7] p-3 text-sm text-[#0b5d1e]">{{message()}}</p>}
@if(session.role()==='doctor'){@for(a of agenda();track a.id){<article class="mt-4 rounded-xl border p-4"><strong class="text-[#002777]">{{a.specialty}}</strong><p class="text-sm">{{a.patient}} · {{a.location}}</p><p class="text-sm text-[#667085]">{{a.startsAt | date:'medium'}}</p><div class="mt-3 flex gap-2"><button (click)="close(a,'COMPLETED')" class="rounded bg-[#006ef4] px-3 py-2 text-sm font-bold text-white">Completada</button><button (click)="close(a,'NO_SHOW')" class="rounded border px-3 py-2 text-sm font-bold">No asistió</button></div></article>}@empty{<p class="mt-4 text-sm text-[#667085]">No hay citas aprobadas en tu agenda.</p>}}
@if(session.role()==='admin'){@for(i of inbox();track i.requestId){<article class="mt-4 rounded-xl border p-4"><strong class="text-[#002777]">{{i.kind === 'RESCHEDULE'?'Reprogramación':'Solicitud especializada'}}</strong><p class="text-sm">{{i.patient}} · {{i.specialty}}</p><p class="text-sm">{{i.professional}} · {{i.locationId}}</p><p class="text-sm text-[#667085]">{{i.startsAt | date:'medium'}}</p></article>}@empty{<p class="mt-4 text-sm text-[#667085]">No hay solicitudes pendientes.</p>}}</section></main>`})
export class OperationsPanel {
 readonly api=inject(OperationsApi); readonly session=inject(AuthSession); readonly agenda=signal<ProfessionalAppointment[]>([]); readonly inbox=signal<InboxItem[]>([]);readonly error=signal('');readonly message=signal('');
 constructor(){this.load();} load(){this.error.set('');if(this.session.role()==='doctor')this.api.agenda().subscribe({next:v=>this.agenda.set(v),error:()=>this.error.set('No fue posible cargar la agenda.')});if(this.session.role()==='admin')this.api.inbox().subscribe({next:v=>this.inbox.set(v),error:()=>this.error.set('No fue posible cargar la bandeja.')});}
 close(a:ProfessionalAppointment,status:'COMPLETED'|'NO_SHOW'){this.api.close(a.id,status).subscribe({next:()=>{this.message.set('Cita cerrada.');this.load();},error:e=>this.error.set(e.error?.message??'No fue posible cerrar la cita.')});}
}
